#INITIAL SETTINGS
data_directory: drive/MyDrive/Colab Notebooks
data_name: train.csv, test_df.csv
intial_columns: 434
drop_columns: 321
target_name: isFraud
test_size: 147635
model_name: XG BOOST


#XGB parameters
colsample_bytree: 0.4
learning_rate: 0.1
max_depth: 20
min_child_weight: 1